create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text not null check (source in ('comingsoon', 'geometrydashiver')),
  created_at timestamptz not null default now()
);

alter table public.subscribers enable row level security;

create index if not exists subscribers_created_at_idx
  on public.subscribers (created_at desc);
